version: 2

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: kubectl-catalog
    main: .
    binary: kubectl-catalog
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/anandf/kubectl-catalog/cmd.version={{.Version}}
      - -X github.com/anandf/kubectl-catalog/cmd.gitCommit={{.ShortCommit}}
      - -X github.com/anandf/kubectl-catalog/cmd.buildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: oc-catalog
    main: .
    binary: oc-catalog
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/anandf/kubectl-catalog/cmd.version={{.Version}}
      - -X github.com/anandf/kubectl-catalog/cmd.gitCommit={{.ShortCommit}}
      - -X github.com/anandf/kubectl-catalog/cmd.buildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: kubectl-catalog
    builds:
      - kubectl-catalog
    format: tar.gz
    name_template: "kubectl-catalog-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

  - id: oc-catalog
    builds:
      - oc-catalog
    format: tar.gz
    name_template: "oc-catalog-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test.json:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: anandf
    name: kubectl-catalog
  draft: false
  prerelease: auto
